server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/unnoba
          jwk-set-uri: http://localhost:8084/realms/unnoba/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/me/notifications/**
        - id: user-social-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**, /social/**, /auth/**, /me/**
        - id: catalog-service
          uri: http://localhost:8082
          predicates:
              - Path=/admin/artists/**, /events/**, /admin/events/**